version: "3"
services:
  ytdl:
    build: .
    ports: 
      - 5000:5000
    volumes:
      - .:/ytdl
      - /mnt/f/Programming/Files:/files
    environment:
      FLASK_DEBUG: True
    restart: unless-stopped
